language: objective-c
sudo: required
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
    - env: OSX=10.10
      os: osx
      osx_image: xcode7.1
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
before_install:
  - brew tap homebrew/versions
  - mkdir -p "$(brew --repo)/Library/Taps/yous"
  - ln -s "$TRAVIS_BUILD_DIR" "$(brew --repo)/Library/Taps/yous/homebrew-fadedrubies"
  - cd "$(brew --repo)/Library/Taps/yous/homebrew-fadedrubies"
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/yous/homebrew-fadedrubies"
  - brew update
  - export HOMEBREW_DEVELOPER="1"
install:
  - brew uninstall openssl098 -f
  - brew install yous/fadedrubies/openssl098
  - brew uninstall gcc48 gcc49 gcc -f
  - if [[ "$OSX" == "10.9" ]]; then
      brew uninstall gcc44 -f;
      brew install homebrew/versions/gcc44;
    fi
  - if [[ "$OSX" != "10.11" ]]; then
      brew uninstall gcc45 gcc46 gcc47 -f;
      brew install homebrew/versions/gcc45;
      brew install homebrew/versions/gcc46;
      brew install homebrew/versions/gcc47;
    fi
  - brew install homebrew/versions/gcc48
  - brew install homebrew/versions/gcc49
  - brew install gcc
script:
  - export TARGET="ruby-1.9.1-p378" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-1.9.1-p429" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-1.9.1-p430" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-1.9.1-p431" && brew install $TARGET && brew test $TARGET
