language: objective-c
sudo: required
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
    - env: OSX=10.10
      os: osx
      osx_image: xcode7.1
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
before_install:
  - brew tap homebrew/versions
  - mkdir -p "$(brew --repo)/Library/Taps/yous"
  - ln -s "$TRAVIS_BUILD_DIR" "$(brew --repo)/Library/Taps/yous/homebrew-fadedrubies"
  - cd "$(brew --repo)/Library/Taps/yous/homebrew-fadedrubies"
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/yous/homebrew-fadedrubies"
  - brew update
install:
  - brew uninstall gcc48 gcc49 gcc -f
  - if [[ "$OSX" == "10.9" ]]; then
      brew uninstall gcc46 -f;
      brew install homebrew/versions/gcc46;
    fi
  - brew install homebrew/versions/gcc48
  - brew install homebrew/versions/gcc49
  - brew install gcc
script:
  - export TARGET="ruby-1.8.6-p420" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-1.8.7-p374" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-1.9.0-5" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-1.9.1-p431" && brew install $TARGET && brew test $TARGET
  - if [[ "$OSX" == "10.9" ]]; then
      export TARGET="ruby-1.9.2-p330" && brew install $TARGET && brew test $TARGET;
    fi
  - export TARGET="ruby-1.9.3-p551" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-2.0.0-p648" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-2.1.10" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-2.2.4" && brew install $TARGET && brew test $TARGET
  - export TARGET="ruby-2.3.0" && brew install $TARGET && brew test $TARGET
  - brew test-bot --tap=yous/fadedrubies
